image: Visual Studio 2017

cache:
  - packages -> **\packages.config, nuget.config
  - tools -> build.cake, build.ps1
  
environment:
  _DOTNET_VERSION: "3.1.101"

install:
  - choco install gitversion.portable -pre -y
  - ps: "[Net.ServicePointManager]::SecurityProtocol = 'Tls12'"
  - ps: Invoke-WebRequest https://dot.net/v1/dotnet-install.ps1 -OutFile dotnet-install.ps1
  - ps: if ((-Not (Test-Path dotnet\dotnet.exe)) -or (((dotnet\dotnet.exe --version) -Join '') -ne $Env:_DOTNET_VERSION)) { dotnet-install.ps1 -Version $Env:_DOTNET_VERSION -InstallDir dotnet } else { $Env:path = $Env:APPVEYOR_BUILD_FOLDER + "\dotnet\dotnet.exe;" + $Env:path }

before_build:
  - ps: gitversion $env:APPVEYOR_BUILD_FOLDER /l console /output buildserver /updateAssemblyInfo /nofetch /b $env:APPVEYOR_REPO_BRANCH

build_script:
  - ps: ./build.ps1

after_build:
  7z a ./AnimeListBot.zip ./artifacts/*

clone_script:
  - cmd: git clone --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
  - cmd: git checkout -f %APPVEYOR_REPO_COMMIT%

test: off

artifacts:
  - path: ./msbuild.log
    name: Build Log
    
  - path: ./AnimeListBot.zip
    name: AnimeListBot
    type: zip

on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL_PASSED
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL_FAILED
