image: Visual Studio 2017

cache:
  - packages -> **\packages.config, nuget.config
  - tools -> build.cake, build.ps1

install:
  - choco install gitversion.portable -pre -y

before_build:
  - ps: gitversion $env:APPVEYOR_BUILD_FOLDER /l console /output buildserver /updateAssemblyInfo /nofetch /b $env:APPVEYOR_REPO_BRANCH

build_script:
  - ps: ./build.ps1
  
after_build:
  7z a ./AnimeListBot.zip ./artifacts/*
  
clone_script:
  - cmd: git clone --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
  - cmd: git checkout -f %APPVEYOR_REPO_COMMIT%

test: off

artifacts:
  - path: ./msbuild.log
    name: Build Log
    
  - path: ./AnimeListBot.zip
    name: AnimeListBot
    type: zip